# Basic
title: Liberxue
subtitle: Liberxue-GitHub「轻博客」.
welcome_message: 欢迎来到我的角落...
description: 我在这里侃侃理想、谈谈人生、敲敲代码，实践梦想时顺便赚钱，by-liberxue
creator: <a href="http://www.liberxue.com">@liberxue</a>

url: "http://www.liberxue.com"

permalink: /:categories/:title

# Format
highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: GitHub,     in_site: false,  description: Liberxue's GitHub,    url: 'https://github.com/liberxue'}
    - {title: 目录,        in_site: true,  description: 博客目录,               url: '/timeline'}
    - {title: 关于,        in_site: true,  description: 关于作者 GcsSloop,       url: '/info/about'}
    


gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-redirect-from

# Pagination
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: GcsSloop
    # duoshuo:
# Social
social:
    weibo:  liberxue
    github: liberxue
    twitter: liberxue
    rss: /feed.xml
    mail: liberxue@gmail.com
    copyright: http://liberxue.com

# Google Analytics
ga:
    id: UA-82493667-1
    host: www.gcssloop.com
